### ISSUE TITLE
py.path.local('/x').dirname should be '/'

### ISSUE THREAD

**Issue by robnagler** [pytest-dev/py#220] opened 2019-04-16 21:10 UTC
`dirname` should be the same as `os.path.dirname` and `local.dirpath()`. Both of these assertions fail:

```py
import os.path
import py
x = py.path.local('/x')
assert x.dirpath() == x.dirname
assert os.path.dirname(str(x)) == x.dirname
```

[`dirpath` uses `os.path.dirname`](https://github.com/pytest-dev/py/blob/78b8794821e93f625e6d07896b7cfd771ff23fd0/py/_path/local.py#L321) and [`dirname` uses `split` and `join`](https://github.com/pytest-dev/py/blob/78b8794821e93f625e6d07896b7cfd771ff23fd0/py/_path/local.py#L298).

**Comment by RonnyPfannschmidt** [comment] 2019-04-17 13:08
`py.path` is correct as per  its design and the spec functionality
https://github.com/pytest-dev/py/blob/78b8794821e93f625e6d07896b7cfd771ff23fd0/py/_path/local.py#L248-L257

note that your code should use https://github.com/pytest-dev/py/blob/78b8794821e93f625e6d07896b7cfd771ff23fd0/py/_path/common.py#L315-L329 to be correct to begin with

**Comment by RonnyPfannschmidt** [comment] 2021-02-27 21:30
closing as not using pylib  as intended

**Closed by RonnyPfannschmidt** 2021-02-27 21:30 UTC
Labels: invalid
