### ISSUE TITLE
`safety` says `py <=1.11.0` is affected by a ReDoS issue but no new release is available

### ISSUE THREAD

**Issue by saher-alhusayan** [pytest-dev/py#290] opened 2022-11-01 15:33 UTC
Safety version: 1.10.3
Python version: 3.10.2
Operating System: MacOS 12.6

## Description 

Hey 👋 

When running `safety check --full-report --file=requirements.txt`, `safety` is failing to pass a check for `py` saying all versions of `py` under or equal to 1.11.0 are affected (see screenshot below). The problem is we can't upgrade to a higher version as none is available.

The error cites [this issue]( https://github.com/pytest-dev/py/issues/287 ) but I can't see any discussion on it or a resolution.

Any idea if someone is aware or a fix is being worked on? 🙏 

![image](https://user-images.githubusercontent.com/56968205/199272853-e29e3463-87d3-4043-8d9d-e24b31850ca3.png)

**Comment by RonnyPfannschmidt** [comment] 2022-11-01 15:46
Duplicate of #288

**Closed by RonnyPfannschmidt** 2022-11-01 15:46 UTC
